# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pageMain(object):
    resized = QtCore.pyqtSignal()
    def setupUi(self, pageMain):
        pageMain.setObjectName("pageMain")
        self.centralwidget = QtWidgets.QWidget(pageMain)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 300, 60, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        pageMain.setCentralWidget(self.centralwidget)

        self.retranslateUi(pageMain)
        QtCore.QMetaObject.connectSlotsByName(pageMain)

    def retranslateUi(self, pageMain):
        _translate = QtCore.QCoreApplication.translate
        pageMain.setWindowTitle(_translate("pageMain", "Seam Carving"))

